language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vanshik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vanshik/react-test npm test

after_success:
  - docker build -t vanshik/multi-client ./client
  - docker build -t vanshik/multi-nginx ./nginx
  - docker build -t vanshik/multi-server ./server
  - docker build -t vanshik/multi-worker ./worker
  #login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push vanshik/multi-client
  - docker push vanshik/multi-nginx
  - docker push vanshik/multi-server
  - docker push vanshik/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-956542856733"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY